---
apiVersion: batch/v1
kind: Job
metadata:
  name: "bitwarden-restore"
  labels:
    app.kubernetes.io/component: bitwarden-restore
    app: bitwarden-restore
spec:
  ttlSecondsAfterFinished: 300
  backoffLimit: 1
  template:
    metadata:
      name: "bitwarden-restore"
      labels:
        app.kubernetes.io/component: bitwarden-restore
        app: bitwarden-restore
    spec:
      initContainers:
      - name: download-minio
        image: "minio/mc"
        env:
        - name: MINIO_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: bitwarden-minio-credentials
              key: accessKey
        - name: MINIO_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: bitwarden-minio-credentials
              key: secretKey
        volumeMounts:
          - name: mssql-backups
            mountPath: /backups
        command:
          - "/bin/sh"
          - "-c"
        args: [
            "
            mc alias set myminio http://192.168.10.121:9000 $MINIO_ACCESS_KEY $MINIO_SECRET_KEY --insecure;
            LATEST=$(mc find myminio/backup-bitwarden --name \"*.bak\" --insecure | sort | tail -1);
            echo \"Téléchargement de $LATEST depuis MinIO...\";
            mc cp \"$LATEST\" /backups/vault.bak --insecure;
            echo 'Téléchargement terminé.'
            "
        ]
      containers:
      - name: restore-db
        image: "mcr.microsoft.com/mssql-tools"
        env:
        - name: MSSQL_CONN_STRING
          valueFrom:
            secretKeyRef:
              name: bitwarden-sql-connection-string
              key: globalSettings__sqlServer__connectionString
        volumeMounts:
          - name: mssql-backups
            mountPath: /backups
        command:
          - "/bin/bash"
          - "-c"
        args: [
            "
            svr=\"$(echo \"${MSSQL_CONN_STRING}\" | grep -Po \"Data Source=tcp:\\K[^,]*(?=.*)\")\";
            pass=\"$(echo \"${MSSQL_CONN_STRING}\" | grep -Po \".*Password=\\K[^;]*(?=.*)\")\";
            /opt/mssql-tools/bin/sqlcmd -S $svr -U SA -P \"$pass\" -Q \"ALTER DATABASE [vault] SET SINGLE_USER WITH ROLLBACK IMMEDIATE; RESTORE DATABASE [vault] FROM DISK = '/var/opt/mssql/backups/vault.bak' WITH REPLACE; ALTER DATABASE [vault] SET MULTI_USER;\"
            "
        ]
      restartPolicy: Never
      volumes:
        - name: mssql-backups
          persistentVolumeClaim:
            claimName: bitwarden-self-host-mssqlbackups
