#!/bin/bash
# Pre-commit hook pour chiffrer les fichiers values.*.yaml

set -e

# Vérification d'openssl
if ! command -v openssl >/dev/null 2>&1; then
    echo "❌ openssl n'est pas installé"
    exit 1
fi

# go to .git 
cd "$(git rev-parse --show-toplevel)"

echo "🔐 Exécution du pre-commit hook - Chiffrement des fichiers values.*.yaml"

VALUES_FILES=$(git diff --cached --name-only | grep -E "values\.(preprod|prod|dev|test)?\.yaml$|^values\.yaml$")

if [ -z "$VALUES_FILES" ]; then
    echo "ℹ️  Aucun fichier values.*.yaml staged pour commit"
    exit 0
fi

echo "📄 Fichiers values.*.yaml trouvés dans le staging area:"
echo "$VALUES_FILES"

# mot de passe
if [ -n "$ENCRYPTION_PASSWORD" ]; then
    echo "🔑 Utilisation du mot de passe depuis la variable d'environnement"
    PASSWORD="$ENCRYPTION_PASSWORD"
else
    echo "🔑 Veuillez entrer le mot de passe pour le chiffrement:"
    
    exec < /dev/tty
    stty -echo
    printf "Mot de passe: "
    read PASSWORD
    stty echo
    printf "\n"
    exec <&-
    
    if [ -z "$PASSWORD" ] || [ ${#PASSWORD} -lt 8 ]; then
        echo "❌ Mot de passe vide ou trop court (min. 8 caractères). Annulation du commit."
        exit 1
    fi
fi

echo "✅ Mot de passe reçu, début du chiffrement..."

# Chiffrement
while IFS= read -r file; do
    if [ -f "$file" ]; then
        encrypted_file="${file}.enc"
        
        echo "🔒 Chiffrement de $file vers $encrypted_file..."
        
        echo "$PASSWORD" | openssl enc -aes-256-cbc -salt -pbkdf2 -iter 100000 -in "$file" -out "$encrypted_file" -pass stdin
        
        if [ $? -eq 0 ]; then
            echo "✅ $file chiffré avec succès"
            
            git add "$encrypted_file"
            
            git reset HEAD "$file"
            
            rm "$file"
            
            echo "✅ Fichier original $file supprimé et remplacé par $encrypted_file"
            
        else
            echo "❌ Erreur lors du chiffrement de $file"
            exit 1
        fi
    fi
done <<< "$VALUES_FILES"

echo "git push -u origin main "

exit 0

